apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: shorturl
  namespace: <%= $.namespace %>
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: shorturl
        app: shorturl
    spec:
      containers:
      - image: mrgalaxy/shorturl:latest
        name: shorturl
        imagePullPolicy: IfNotPresent
        args:
        - "--redis.host=redis"
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /
            port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: shorturl
  namespace: <%= $.namespace %>
  labels:
    name: shorturl
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    name: shorturl
