<% if (!$.domain) {
  throw new Error("Missing domain option.")
} %>

apiVersion: extensions/v1beta4
kind: Ingress
metadata:
  name: ingress
  namespace: <%= $.namespace %>
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    # unlike most services, we don't want to add an extra redirect with short urls
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls:
  - secretName: shorturl-certs
    hosts:
    - <%= $.domain %>
  rules:
  - host: <%= $.domain %>
    http:
      paths:
      - path: /
        backend:
          serviceName: shorturl
          servicePort: http
