<% if (!$.domain) {
  throw new Error("Missing domain option.")
} %>

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: <%= $.namespace %>
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - secretName: shorturl-ssl
    hosts:
    - <%= $.domain %>
  rules:
  - host: <%= $.domain %>
    http:
      paths:
      - path: /
        backend:
          serviceName: shorturl
          servicePort: http
